#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    https://shiny.posit.co/
#


library(shiny)

library(httr)
library(shinyjs)
library(openai)
library(shinybusy)





ui <- fluidPage(
  useShinyjs(),
  tags$head(
    tags$style(HTML("
      /* this will affect all the pre elements */
      pre {
        color: red;
        background-color: #5ef4fb;
      }
      /* this will affect only the pre elements under the class myclass */
      .myclass pre {
        color: black;
        background-color: #F0E68C;
        font-weight: bolder;
        width: 700px; 
        max-width: 100%;
        white-space: pre-wrap; #wraps text
        word-break:initial;  #prevents word break
      }"))),
  
  
  titlePanel("DnD 5e API - Monster Lookup"),
  HTML(
    paste(
      h4("This App uses dnd5eapi.co for stat bocks"),
      h4("Images generated by pollinations AI"),'<br/>'
    )
  ),
  
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput("monster_name", "Select a Monster:", choices = NULL),
      
      actionButton("fetch", "Fetch Data")
      
    ),
    
    mainPanel(
      uiOutput("monster_image"),
      div(class = "myclass",
          verbatimTextOutput("monster_data")
      )
      
    )
    
  )
  
)







server <-function(input, output, session) {
  
  
  
  
  fetch_condition_name <- function(api_url) {
    
    
    response <- GET(paste0("https://www.dnd5eapi.co", api_url))
    
    if (status_code(response) == 200) {
      
      condition <- content(response, "parsed")
      
      return(condition$name)
      
    } else {
      
      return(api_url)
      
    }
    
  }
  
  
  
  update_monster_list <- function() {
    
    response <- GET('https://www.dnd5eapi.co/api/monsters')
    
    if (status_code(response) == 200) {
      
      monsters <- content(response, "parsed")
      
      monster_names <- sapply(monsters$results, function(monster) monster$name)
      
      monster_indices <- sapply(monsters$results, function(monster) monster$index)
      
      updateSelectInput(session, "monster_name", choices = c(Choose = '', setNames(monster_indices, monster_names)))
      
    } else {
      
      showNotification("Failed to fetch monster list", type = "error")
      
    }
    
  }
  
  
  
  update_monster_list()
  


  observeEvent(input$fetch, {
    

    req(input$monster_name)
    
    # Reset image_loaded to FALSE
    runjs("Shiny.setInputValue('image_loaded', false);")
    
    # Activate merging gif ----
    show_modal_gif(
      src = 'forging.gif',
      text = 'Forging Data...',
      height = '220px',
      width = '220px',
      modal_size = 's'
    )
    
    monster_index <- input$monster_name
    
    url <- paste0('https://www.dnd5eapi.co/api/monsters/', monster_index)
    
    
    
    response <- GET(url)
    
    
    
    if (status_code(response) == 200) {
      
      monster <- content(response, "parsed")
      
      if (!is.null(monster$name)) {
        

        
        #generate image #################################################################################
        
 
    

        
        monster_img <-input$monster_name
        
        image_url <- paste("https://image.pollinations.ai/prompt/","D&D monster illustration of", monster_img, ".png")
        
        
        
        
        
        output$monster_image <- renderUI({
          tags$img(
            src = image_url,
            alt = monster$name,
            width = "50%",
            onload = "Shiny.setInputValue('image_loaded', true);"
          )
        })
        
        
 
       

        

        
        output$monster_data <- renderText({monster_info})
        
     
        ### API data################################################
        
        armor_class <- sapply(monster$armor_class, function(ac) {
          
          if (is.numeric(ac)) {
            
            return(as.character(ac))
            
          } else if (is.list(ac) && !is.null(ac$value)) {
            
            return(as.character(ac$value))
            
          } else {
            
            return(NULL)
            
          }
          
        })
        
        armor_class <- paste(armor_class[!is.null(armor_class)], collapse = ', ')
        
        
        
        condition_immunities <- sapply(monster$condition_immunities, function(ci) {
          
          if (!is.null(ci$url)) {
            
            return(fetch_condition_name(ci$url))
            
          } else {
            
            return(ci.name)
            
          }
          
        })
        
        
        
        monster_info <- paste(
          
          "Name: ", monster$name, "\n",
          
          "Type: ", monster$type, "\n",
          
          "Alignment: ", monster$alignment, "\n",
          
          "Size: ", monster$size, "\n",
          
          "Hit Points: ", monster$hit_points, "\n",
          
          "Armor Class: ", armor_class, "\n",
          
          "Challenge Rating: ", monster$challenge_rating, "\n",
          
          "Strength: ", monster$strength, "\n",
          
          "Dexterity: ", monster$dexterity, "\n",
          
          "Constitution: ", monster$constitution, "\n",
          
          "Intelligence: ", monster$intelligence, "\n",
          
          "Wisdom: ", monster$wisdom, "\n",
          
          "Charisma: ", monster$charisma, "\n",
          
          "Languages: ", monster$languages, "\n",
          
          "Speed: ", toString(unlist(monster$speed)), "\n",
          
          "Senses: ", toString(unlist(monster$senses)), "\n",
          
          "Damage Vulnerabilities: ", toString(unlist(monster$damage_vulnerabilities)), "\n",
          
          "Damage Resistances: ", toString(unlist(monster$damage_resistances)), "\n",
          
          "Damage Immunities: ", toString(unlist(monster$damage_immunities)), "\n",
          
          "Condition Immunities: ", toString(unlist(condition_immunities)), "\n",
          
          sep = ""
          
        )
        
        
        
        if (length(monster$actions) > 0) {
          
          actions <- paste(sapply(monster$actions, function(action) {
            
            paste("Action: ", action$name, "\n", action$desc, "\n", sep = "")
            
          }), collapse = "\n")
          
          monster_info <- paste(monster_info, "Actions:\n", actions, sep = "\n")
          
        }
        
        
        
        if (length(monster$special_abilities) > 0) {
          
          special_abilities <- paste(sapply(monster$special_abilities, function(sa) {
            
            paste("Special Ability: ", sa$name, "\n", sa$desc, "\n", sep = "")
            
          }), collapse = "\n")
          
          monster_info <- paste(monster_info, "Special Abilities:\n", special_abilities, sep = "\n")
          
        }
        
        
        
        if (length(monster$legendary_actions) > 0) {
          
          legendary_actions <- paste(sapply(monster$legendary_actions, function(la) {
            
            paste("Legendary Action: ", la$name, "\n", la$desc, "\n", sep = "")
            
          }), collapse = "\n")
          
          monster_info <- paste(monster_info, "Legendary Actions:\n", legendary_actions, sep = "\n")
          
        }
        
        
        
        if (!is.null(monster$desc)) {
          
          monster_info <- paste(monster_info, "Description: ", monster$desc, sep = "\n")
          
        }
        
      } 
      else {
        
        monster_info <- "Monster not found"
        
        output$monster_data <- renderText({monster_info})
        
      }
      
    } else {
      
      monster_info <- "Error fetching data"
      
      output$monster_data <- renderText({monster_info})
      
    }
    # Remove the modal GIF after the image is fully loaded

  })

  # Remove the modal GIF after the image is fully loaded
  observeEvent(input$image_loaded, {
    if (input$image_loaded) {
      remove_modal_gif()
    }
  })
  

}



# Run the application

shinyApp(ui = ui, server = server)
